### ISSUE TITLE
Contao 4 Kompatibilität

### ISSUE THREAD

**Issue by 9teufel** [terminal42/contao-autoregistration#1]
Habe versucht die Erweiterung manuell zu installieren.
DB Update wurde auch gemacht, nur sehe ich keine Änderung im Registrierungs Modul.

Sind gröbere Anpassungen notwendig damit's unter Contao 4.4 läuft?

**Comment by qzminski** [comment]
The new fields are added to the **website root settings** and not to the registration module.

The extension seems to work with Contao 4.4 just fine.

**Comment by rustykowski** [comment]
Yes, it works fine also in Contao 4.4.7 (with manual installation).
Very helpful extension!
Will you occasionally adjust it for composer?

**Comment by aschempp** [comment]
This extension will most likely break with 4.5 (see https://github.com/contao/core-bundle/pull/685), so we need to rewrite it anyway…
