### ISSUE TITLE
Missing Release V3

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-autoregistration#11]
The README says that in Version 3 the configuration is done via the module. But there is no version 3.
I have installed the `dev-main`, that is then probably the V3. Because there was the configuration in the module.

Maybe you could tag and release the V3 officially.
Thanks

**Comment by contaoacademy** [comment]
Friendly reminder…
Would you like to add a tag for Version V3?

**Comment by fritzmg** [comment]
V3 might not be ready yet for a stable release.

The README on GitHub will always show the version of the default branch. If you want to read the README of the latest release, you'll have to browse the repository accordingly: https://github.com/terminal42/contao-autoregistration/blob/2.1.0/README.md

**Comment by contaoacademy** [comment]
> The README on GitHub will always show the version of the default branch. If you want to read the README of the latest release, you'll have to browse the repository accordingly: https://github.com/terminal42/contao-autoregistration/blob/2.1.0/README.md

Thanks, @fritzmg, for your explanation. I actually overlooked that…

Question would be now, when will the V3 be release. I have the `dev-main` now in several installations running and so far, had no problems. (only Contao 4.9 tested)

**Comment by aschempp** [comment]
3.0.0 has been released 🙃
