### ISSUE TITLE
Redirect page not effectiv

### ISSUE THREAD

**Issue by Ernestopheles** [terminal42/contao-autoregistration#14]
Contao 4.13.16; PHP 8.1

Obviously at least since Sept. 2022 the selected redirection page in the registration modul (confirmation page) is not effectiv. The useris led to the page he startet registration after clicking the registration link in his Email.

I assume this has to do with this extension, but not for sure.

**Comment by aschempp** [comment]
The extension does not redirect at all, it only activates user accounts. If you can debug this and find the actual issue, I would be happy to merge a pull request 😊
