### ISSUE TITLE
Options in registration modul missleading

### ISSUE THREAD

**Issue by Ernestopheles** [terminal42/contao-autoregistration#15]
Contao 4.13.16; PHP 8.1

Heading is
```
Mitgliederkonto aktivieren
```

The options of `´`Mitgliederkonto aktivieren``` in registration module are 

```
 Nicht aktivieren
 Konto aktivieren
 Aktivieren und sofort anmelden
```

 with this label

```
Neue Mitglieder automatisch aktivieren und anmelden (ohne E-Mail-Bestätigung).
``` 

This is missleading, as this extension is about 

> The extension allows to automatically login a Contao user after registration or when the account is activated.

So in case the system is configured to use double-opt-in and the user clicks the registration link, it's not about activating the member-account (so heading is wrong for this case). Also options 1 and 2 are senseless then. Only option 3 is partly meaningful, and this is what I wouls expect to have: To be able to choose if after registration the user will be automatically logged in or not. 

I did not use the modus without double-opt-in. I assume then these options will be meaningful.

My suggestion:
Separate the account-activation options from the automatically login options. Like so:

```
Mitgliederkonto für neue Mitglieder ohne E-Mail Bestätigung automatisch aktivieren? - checkbox

``` 

```
Neue Mitglieder sofort nach Registrierung einmalig automatisch anmelden (ohne Login-Formular)? - checkbox

```

**Comment by aschempp** [comment]
I agree this can be confusing (I was confused myself today), but I don't think we can change that without breaking stuff. I'll therefore leave this up to better documentation.
