### ISSUE TITLE
Installation per Contao Manager funktionier nicht.

### ISSUE THREAD

**Issue by mueller-steinhauer** [terminal42/contao-autoregistration#3]
Hallo zusammen, 

ich bin gerade auf eure Erweiterung gestoßen und habe versucht diese unter Contao 4.4.18 zu installieren.

Bekomme folgenden Fehlercode:
In InitCommand.php line 718:
                                                                               
  Could not find a version of package terminal42/contao-autoregistration matc  
  hing your minimum-stability (stable). Require it with an explicit version c  
  onstraint allowing its desired stability.                                    
                                                                               

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

# Process terminated with exit code 1
# Result: General error

**Comment by Toflar** [comment]
Weil sie nicht freigegeben war für Contao 4, von daher hat das schon gestimmt 😄 Probier's mit Version 2.
