### ISSUE TITLE
Contao 4 Kompatibilität terminal42/contao-autoregistration

### ISSUE THREAD

**Issue by designpilot** [terminal42/contao-autoregistration#5]
Hi Andreas
You have the Version 2.0.0 and 2.0.1 of the Extension online and his only for Contao 4.5 above, can you write the Extension for the Version 4.4.x of Contao ???

**Comment by aschempp** [comment]
You can manually install the 1.x version in the `system/modules` directory. It should work fine with Contao 4.4

**Comment by manjarco** [comment]
Manual install seems to not work properly (or am I just to stupid to install an extension manually?).

On trying to register a new member it throws this error:

> app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AutoRegistration\" from the global namespace.\nDid you forget a \"use\" statement?

The member is generated in the database nontheless, but no E-Mail is sent.

C 4.4.32
Autoregistration 1.3.0

**Comment by fritzmg** [comment]
Did you rebuild the Symfony Application Cache after manual installation?

**Comment by manjarco** [comment]
Just to be safe I did everything you can do in the maintanance section of the manager and contao. 😬

**Comment by sgei** [comment]
Hi,
I have the same problem.
Contao 4.4 is the official LTS version. Please make it possible to install the bundle via contao manager.

Steffen

**Comment by richardhj** [comment]
There is no way that version 2 of this extension can be compatible with Contao 4.4.
You should be able to install version 1.

**Comment by Asfga** [comment]
Is there still a version 1.x available?

**Comment by richardhj** [comment]
https://github.com/terminal42/contao-autoregistration/releases/tag/1.3.0

**Comment by Asfga** [comment]
Thanks! I copied the folder into system/modules like you wrote in the other closed issue, cleared the production cache and opened the install tool but nothing has to be updated there. It's also not shown in the package overview in the contao manager. Any ideas why?

Edit: Had to create the symlinks new.
